language: node_js
node_js: v12.11.1
cache:
  npm: true
  directories:
    - node_modules
branches:
  except:
    - develop
  only:
    - master
env:
  - project=webui
install:
  - npm i gulp@3.9.1 -g
  - npm i
  - gulp -v
before_script:
  - echo "before script"
script:
  - gulp
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_OAUTH_TOKEN"
  keep_history: false
  local_dir: dist
  on:
    branch: master
after_script:
  - echo "success"
