language: node_js
node_js: v10.16.0
cache:
  npm: true
  directories:
    - node_modules
branches:
  except:
    - develop
  only:
    - master
env:
  - project=htmlCollect
install:
  - npm i gulp-cli -g
  - npm i
  - gulp -v
before_script:
  - echo "before script"
script:
  - export date=`date`
  - BUILD_TIME=$date gulp
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_OAUTH_TOKEN"
  keep_history: false
  local_dir: dist
  on:
    branch: master
after_script:
  - echo "success"
