name: gulp CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn add gulp-cli -g
          yarn install
          gulp -v
          export date=`date`
          BUILD_TIME=$date gulp
          ls
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.gt }}
